apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ .Release.Name }}-quota"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: agentit
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
    services: "10"