{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: agentit
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
