"""Tests for meaningful CycloneDX SBOM inventory (sbom-artifact)."""
from __future__ import annotations

import json

from agentit.remediation.clear_evidence import verify_sbom_file
from agentit.remediation.sbom_build import (
    components_from_manifests,
    enrich_sbom_artifact_files,
)


def test_components_from_requirements() -> None:
    comps = components_from_manifests({
        "requirements.txt": "flask==3.0.0\nrequests>=2.31.0\n# comment\n",
    })
    names = {c["name"] for c in comps}
    assert "flask" in names
    assert "requests" in names
    flask = next(c for c in comps if c["name"] == "flask")
    assert flask.get("version") == "3.0.0"
    assert flask.get("purl", "").startswith("pkg:pypi/flask")


def test_components_from_package_json() -> None:
    comps = components_from_manifests({
        "package.json": json.dumps({
            "dependencies": {"express": "^4.18.2"},
            "devDependencies": {"typescript": "~5.3.0"},
        }),
    })
    names = {c["name"] for c in comps}
    assert names == {"express", "typescript"}


def test_components_from_go_mod() -> None:
    comps = components_from_manifests({
        "go.mod": (
            "module example.com/app\n\ngo 1.22\n\n"
            "require (\n"
            "\tgithub.com/gin-gonic/gin v1.9.1\n"
            ")\n"
        ),
    })
    assert any(c["name"] == "github.com/gin-gonic/gin" for c in comps)


def test_enrich_populates_empty_shell() -> None:
    files = [{
        "target_path": "sbom.cdx.json",
        "skill_name": "sbom-artifact",
        "content": json.dumps({
            "bomFormat": "CycloneDX",
            "specVersion": "1.5",
            "metadata": {"component": {"type": "application", "name": "pulse"}},
            "components": [],
        }) + "\n",
        "description": "Generated by skill sbom-artifact",
    }]
    manifests = {
        "requirements.txt": "fastapi==0.110.0\nuvicorn==0.27.0\n",
    }

    def read_file(path: str) -> str | None:
        return manifests.get(path)

    enriched = enrich_sbom_artifact_files(
        files,
        read_file=read_file,
        tree_paths=list(manifests),
        app_name="pulse-agent",
    )
    doc = json.loads(enriched[0]["content"])
    assert len(doc["components"]) >= 2
    ok, reason = verify_sbom_file(enriched)
    assert ok, reason


def test_enrich_leaves_populated_bom() -> None:
    content = json.dumps({
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "components": [{"type": "library", "name": "already", "version": "1"}],
    }) + "\n"
    files = [{
        "target_path": "sbom.cdx.json",
        "skill_name": "sbom-artifact",
        "content": content,
    }]
    enriched = enrich_sbom_artifact_files(
        files,
        read_file=lambda p: "flask==1.0\n",
        tree_paths=["requirements.txt"],
    )
    assert enriched[0]["content"] == content
