{{- if .Values.argoEvents.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  nats:
    native:
      replicas: 3
{{- end }}
