"""Skill engine — loads Markdown skill definitions, matches them to findings, renders templates."""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from agentit.agents.base import GeneratedFile
from agentit.models import AssessmentReport
from agentit.platform_context import PlatformContext

logger = logging.getLogger(__name__)


@dataclass
class Skill:
    """A single skill definition loaded from a Markdown file with YAML frontmatter."""

    name: str
    domain: str
    version: int
    triggers: list[str]
    outputs: list[str]
    property_description: str
    body: str
    file_path: str
    mode: str = "template"

    def matches(self, report: AssessmentReport) -> bool:
        """Return True if any trigger keyword appears in the report findings."""
        haystack = _report_text(report).lower()
        return any(t.lower() in haystack for t in self.triggers)


def _report_text(report: AssessmentReport) -> str:
    """Flatten a report into a single searchable string."""
    parts = [report.summary]
    for score in report.scores:
        parts.append(score.dimension)
        for f in score.findings:
            parts.extend([f.category, f.description, f.recommendation])
    return " ".join(parts)


def load_skill(path: Path) -> Skill | None:
    """Parse a Markdown file with YAML frontmatter into a Skill."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.warning("Cannot read skill file %s: %s", path, exc)
        return None

    # Split frontmatter from body
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if not match:
        logger.warning("No YAML frontmatter in %s", path)
        return None

    try:
        meta = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        logger.warning("Bad YAML frontmatter in %s: %s", path, exc)
        return None

    if not isinstance(meta, dict):
        return None

    required = {"name", "domain", "version", "triggers", "outputs"}
    missing = required - set(meta.keys())
    if missing:
        logger.warning("Skill %s missing fields: %s", path, missing)
        return None

    return Skill(
        name=meta["name"],
        domain=meta["domain"],
        version=int(meta["version"]),
        triggers=list(meta["triggers"]),
        outputs=list(meta["outputs"]),
        property_description=meta.get("property", ""),
        body=match.group(2),
        file_path=str(path),
        mode=meta.get("mode", "template"),
    )


class SkillEngine:
    """Loads skills from a directory and applies them to assessment reports."""

    def __init__(self, skills_dir: Path, *, platform: PlatformContext | None = None) -> None:
        self.skills_dir = skills_dir
        self.platform = platform
        self.skills: list[Skill] = []
        self._load_all()

    def _load_all(self) -> None:
        if not self.skills_dir.is_dir():
            logger.debug("Skills directory does not exist: %s", self.skills_dir)
            return
        for md in sorted(self.skills_dir.rglob("*.md")):
            skill = load_skill(md)
            if skill is not None:
                self.skills.append(skill)
        logger.info("Loaded %d skills from %s", len(self.skills), self.skills_dir)

    def match(self, report: AssessmentReport) -> list[Skill]:
        """Return all skills whose triggers match the report."""
        return [s for s in self.skills if s.matches(report)]

    def generate(self, skill: Skill, report: AssessmentReport) -> list[GeneratedFile]:
        """Render a skill's template against the report. Returns generated files."""
        if skill.mode != "template":
            return []

        template_text = _extract_template(skill.body)
        if not template_text:
            return []

        app_name = report.repo_name.lower().replace("_", "-").replace(".", "-")[:63].strip("-") or "app"
        rendered = template_text.replace("{{app_name}}", app_name)

        # Check if the output kind is available on the platform
        if self.platform:
            for output_kind in skill.outputs:
                if not self.platform.has_api(output_kind.lower() + "s") and not self.platform.has_api(output_kind.lower()):
                    logger.debug("Skipping skill %s: %s not available", skill.name, output_kind)
                    return []

        return [GeneratedFile(
            path=f"{app_name}-{skill.name}.yaml",
            content=rendered,
            description=f"Generated by skill {skill.name}",
            finding_addressed=skill.property_description,
        )]

    def find_uncovered_findings(
        self,
        report: AssessmentReport,
        generated_files: list[GeneratedFile],
    ) -> list[str]:
        """Return finding descriptions not addressed by any generated file."""
        addressed = {f.finding_addressed.lower() for f in generated_files if f.finding_addressed}
        uncovered: list[str] = []
        for score in report.scores:
            for finding in score.findings:
                desc = finding.description.lower()
                if desc not in addressed:
                    uncovered.append(finding.description)
        return uncovered


def _extract_template(body: str) -> str | None:
    """Pull a YAML code block from a skill's Markdown body."""
    match = re.search(r"```ya?ml\s*\n(.*?)```", body, re.DOTALL)
    return match.group(1).strip() if match else None
