from __future__ import annotations

import base64
import logging
import os
from pathlib import Path

import requests

logger = logging.getLogger(__name__)

_API = "https://api.github.com"


def _get_token() -> str:
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        raise RuntimeError("GITHUB_TOKEN env var not set — cannot create PR")
    return token


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    path = repo_url.rstrip("/").removesuffix(".git")
    parts = path.split("/")
    return parts[-2], parts[-1]


def create_onboarding_pr(
    repo_url: str,
    repo_name: str,
    files: list[dict],
    branch_name: str = "agentit/onboarding",
) -> dict:
    """Create a PR with onboarding manifests using the GitHub API.

    No git clone needed — uses the GitHub REST API directly.
    Requires GITHUB_TOKEN env var.
    """
    try:
        token = _get_token()
        hdrs = _headers(token)
        owner, repo = _parse_owner_repo(repo_url)
        base_url = f"{_API}/repos/{owner}/{repo}"

        resp = requests.get(f"{base_url}", headers=hdrs, timeout=10)
        resp.raise_for_status()
        default_branch = resp.json()["default_branch"]

        resp = requests.get(
            f"{base_url}/git/ref/heads/{default_branch}",
            headers=hdrs, timeout=10,
        )
        resp.raise_for_status()
        base_sha = resp.json()["object"]["sha"]

        tree_items = []
        for f in files:
            category = f["category"]
            filename = Path(f["path"]).name
            tree_items.append({
                "path": f".agentit/{category}/{filename}",
                "mode": "100644",
                "type": "blob",
                "content": f["content"],
            })

        resp = requests.post(
            f"{base_url}/git/trees",
            headers=hdrs, timeout=30,
            json={"base_tree": base_sha, "tree": tree_items},
        )
        resp.raise_for_status()
        tree_sha = resp.json()["sha"]

        resp = requests.post(
            f"{base_url}/git/commits",
            headers=hdrs, timeout=10,
            json={
                "message": "feat: add AgentIT enterprise onboarding manifests\n\nGenerated by AgentIT Enterprise Readiness Platform",
                "tree": tree_sha,
                "parents": [base_sha],
            },
        )
        resp.raise_for_status()
        commit_sha = resp.json()["sha"]

        resp = requests.post(
            f"{base_url}/git/refs",
            headers=hdrs, timeout=10,
            json={"ref": f"refs/heads/{branch_name}", "sha": commit_sha},
        )
        if resp.status_code == 422:
            requests.patch(
                f"{base_url}/git/refs/heads/{branch_name}",
                headers=hdrs, timeout=10,
                json={"sha": commit_sha, "force": True},
            ).raise_for_status()
        else:
            resp.raise_for_status()

        file_list = "\n".join(
            f"- `.agentit/{f['category']}/{Path(f['path']).name}` — {f['description']}"
            for f in files
        )
        pr_body = (
            "## AgentIT Enterprise Onboarding\n\n"
            "This PR adds enterprise-readiness manifests generated by AgentIT.\n\n"
            "### Generated Manifests\n"
            f"{file_list}\n\n"
            "> Generated by [AgentIT](https://github.com/alimobrem/AgentIT)"
        )

        resp = requests.post(
            f"{base_url}/pulls",
            headers=hdrs, timeout=10,
            json={
                "title": "AgentIT Enterprise Onboarding",
                "body": pr_body,
                "head": branch_name,
                "base": default_branch,
            },
        )
        if resp.status_code == 422 and "pull request already exists" in resp.text.lower():
            return {"pr_url": f"{repo_url}/compare/{branch_name}", "branch": branch_name, "files_added": len(files)}
        resp.raise_for_status()

        pr_url = resp.json()["html_url"]
        return {"pr_url": pr_url, "branch": branch_name, "files_added": len(files)}

    except requests.HTTPError as exc:
        msg = exc.response.text if exc.response else str(exc)
        logger.exception("GitHub API error creating PR")
        return {"error": f"GitHub API error: {msg[:200]}"}
    except Exception as exc:
        logger.exception("Failed to create PR")
        return {"error": str(exc)}


def create_agent_prs(
    repo_url: str,
    repo_name: str,
    agent_results: list[dict],
) -> list[dict]:
    """Create per-agent branches and PRs via the GitHub API.

    Each agent gets its own branch (agentit/{agent_name}) and PR with
    only that agent's generated files.

    agent_results: [{agent_name, category, files: [{path, content, description}]}]
    Returns: [{agent_name, pr_url, branch, error}]
    """
    try:
        token = _get_token()
        hdrs = _headers(token)
        owner, repo = _parse_owner_repo(repo_url)
        base_url = f"{_API}/repos/{owner}/{repo}"

        resp = requests.get(base_url, headers=hdrs, timeout=10)
        resp.raise_for_status()
        default_branch = resp.json()["default_branch"]

        resp = requests.get(
            f"{base_url}/git/ref/heads/{default_branch}",
            headers=hdrs, timeout=10,
        )
        resp.raise_for_status()
        base_sha = resp.json()["object"]["sha"]
    except Exception as exc:
        logger.exception("Failed to get repo info for per-agent PRs")
        return [{"agent_name": "setup", "error": str(exc)}]

    results: list[dict] = []

    for agent in agent_results:
        agent_name = agent["agent_name"]
        category = agent["category"]
        files = agent.get("files", [])
        if not files:
            continue

        branch_name = f"agentit/{agent_name}"

        try:
            tree_items = []
            for f in files:
                filename = Path(f["path"]).name
                tree_items.append({
                    "path": f".agentit/{category}/{filename}",
                    "mode": "100644",
                    "type": "blob",
                    "content": f["content"],
                })

            resp = requests.post(
                f"{base_url}/git/trees",
                headers=hdrs, timeout=30,
                json={"base_tree": base_sha, "tree": tree_items},
            )
            resp.raise_for_status()
            tree_sha = resp.json()["sha"]

            resp = requests.post(
                f"{base_url}/git/commits",
                headers=hdrs, timeout=10,
                json={
                    "message": f"feat(agentit): {agent_name} — {len(files)} manifests for {repo_name}",
                    "tree": tree_sha,
                    "parents": [base_sha],
                },
            )
            resp.raise_for_status()
            commit_sha = resp.json()["sha"]

            resp = requests.post(
                f"{base_url}/git/refs",
                headers=hdrs, timeout=10,
                json={"ref": f"refs/heads/{branch_name}", "sha": commit_sha},
            )
            if resp.status_code == 422:
                requests.patch(
                    f"{base_url}/git/refs/heads/{branch_name}",
                    headers=hdrs, timeout=10,
                    json={"sha": commit_sha, "force": True},
                ).raise_for_status()
            else:
                resp.raise_for_status()

            file_list = "\n".join(
                f"- `.agentit/{category}/{Path(f['path']).name}`"
                for f in files
            )
            pr_body = (
                f"## AgentIT: {agent_name}\n\n"
                f"Manifests generated by the **{agent_name}** agent.\n\n"
                f"### Files\n{file_list}\n\n"
                f"> Generated by [AgentIT](https://github.com/alimobrem/AgentIT)"
            )

            resp = requests.post(
                f"{base_url}/pulls",
                headers=hdrs, timeout=10,
                json={
                    "title": f"[AgentIT] {agent_name}: {len(files)} manifests for {repo_name}",
                    "body": pr_body,
                    "head": branch_name,
                    "base": default_branch,
                },
            )
            if resp.status_code == 422 and "pull request already exists" in resp.text.lower():
                pr_url = f"{repo_url}/compare/{branch_name}"
            else:
                resp.raise_for_status()
                pr_url = resp.json()["html_url"]

            results.append({
                "agent_name": agent_name,
                "branch": branch_name,
                "pr_url": pr_url,
                "files_count": len(files),
            })

        except Exception as exc:
            logger.warning("Failed to create PR for agent %s: %s", agent_name, exc)
            results.append({
                "agent_name": agent_name,
                "error": str(exc),
            })

    return results


def commit_to_infra_repo(
    infra_repo_url: str,
    app_name: str,
    files: list[dict],
    branch_name: str | None = None,
) -> dict:
    """Commit onboarding manifests to the GitOps infra repo.

    Files are placed under apps/{app_name}/{category}/{filename}.
    Creates a branch and PR if branch_name is set, otherwise commits to main.

    Returns {"commit_url", "pr_url", "files_committed"} or {"error"}.
    """
    branch_name = branch_name or f"agentit/{app_name}"

    try:
        token = _get_token()
        hdrs = _headers(token)
        owner, repo = _parse_owner_repo(infra_repo_url)
        base_url = f"{_API}/repos/{owner}/{repo}"

        resp = requests.get(base_url, headers=hdrs, timeout=10)
        resp.raise_for_status()
        default_branch = resp.json()["default_branch"]

        resp = requests.get(
            f"{base_url}/git/ref/heads/{default_branch}",
            headers=hdrs, timeout=10,
        )
        resp.raise_for_status()
        base_sha = resp.json()["object"]["sha"]

        tree_items = []
        for f in files:
            category = f.get("category", "misc")
            filename = Path(f["path"]).name
            tree_items.append({
                "path": f"apps/{app_name}/{category}/{filename}",
                "mode": "100644",
                "type": "blob",
                "content": f["content"],
            })

        resp = requests.post(
            f"{base_url}/git/trees",
            headers=hdrs, timeout=30,
            json={"base_tree": base_sha, "tree": tree_items},
        )
        resp.raise_for_status()
        tree_sha = resp.json()["sha"]

        resp = requests.post(
            f"{base_url}/git/commits",
            headers=hdrs, timeout=10,
            json={
                "message": f"feat(agentit): onboard {app_name} — {len(files)} manifests",
                "tree": tree_sha,
                "parents": [base_sha],
            },
        )
        resp.raise_for_status()
        commit_sha = resp.json()["sha"]

        resp = requests.post(
            f"{base_url}/git/refs",
            headers=hdrs, timeout=10,
            json={"ref": f"refs/heads/{branch_name}", "sha": commit_sha},
        )
        if resp.status_code == 422:
            requests.patch(
                f"{base_url}/git/refs/heads/{branch_name}",
                headers=hdrs, timeout=10,
                json={"sha": commit_sha, "force": True},
            ).raise_for_status()
        else:
            resp.raise_for_status()

        file_list = "\n".join(
            f"- `apps/{app_name}/{f.get('category', 'misc')}/{Path(f['path']).name}`"
            for f in files
        )
        pr_body = (
            f"## AgentIT: onboard {app_name}\n\n"
            f"Manifests committed to the GitOps infra repo.\n\n"
            f"### Files\n{file_list}\n\n"
            f"> Generated by [AgentIT](https://github.com/alimobrem/AgentIT)"
        )

        resp = requests.post(
            f"{base_url}/pulls",
            headers=hdrs, timeout=10,
            json={
                "title": f"[AgentIT] Onboard {app_name}",
                "body": pr_body,
                "head": branch_name,
                "base": default_branch,
            },
        )
        if resp.status_code == 422 and "pull request already exists" in resp.text.lower():
            pr_url = f"{infra_repo_url}/compare/{branch_name}"
        else:
            resp.raise_for_status()
            pr_url = resp.json()["html_url"]

        return {
            "pr_url": pr_url,
            "commit_url": f"{infra_repo_url}/commit/{commit_sha}",
            "branch": branch_name,
            "files_committed": len(files),
        }

    except requests.HTTPError as exc:
        msg = exc.response.text if exc.response else str(exc)
        logger.exception("GitHub API error committing to infra repo")
        return {"error": f"GitHub API error: {msg[:200]}"}
    except Exception as exc:
        logger.exception("Failed to commit to infra repo")
        return {"error": str(exc)}


def ensure_infra_repo(owner: str, repo_name: str = "agentit-gitops") -> dict:
    """Create a GitOps infra repo if it doesn't exist. Returns {"repo_url"} or {"error"}.

    Checks if the repo exists first. If not, creates it with a README
    and apps/ directory structure.
    """
    try:
        token = _get_token()
        hdrs = _headers(token)
        repo_url = f"https://github.com/{owner}/{repo_name}"

        resp = requests.get(f"{_API}/repos/{owner}/{repo_name}", headers=hdrs, timeout=10)
        if resp.status_code == 200:
            return {"repo_url": repo_url, "created": False}

        resp = requests.post(
            f"{_API}/user/repos",
            headers=hdrs, timeout=10,
            json={
                "name": repo_name,
                "description": "AgentIT GitOps infrastructure — managed by AgentIT agents",
                "private": False,
                "auto_init": True,
            },
        )
        if resp.status_code == 422:
            resp = requests.post(
                f"{_API}/orgs/{owner}/repos",
                headers=hdrs, timeout=10,
                json={
                    "name": repo_name,
                    "description": "AgentIT GitOps infrastructure — managed by AgentIT agents",
                    "private": False,
                    "auto_init": True,
                },
            )
        resp.raise_for_status()
        created_url = resp.json().get("html_url", repo_url)

        requests.put(
            f"{_API}/repos/{owner}/{repo_name}/contents/apps/.gitkeep",
            headers=hdrs, timeout=10,
            json={
                "message": "chore: initialize apps directory for managed applications",
                "content": base64.b64encode(b"").decode(),
            },
        )

        logger.info("Created infra repo: %s", created_url)
        return {"repo_url": created_url, "created": True}

    except Exception as exc:
        logger.exception("Failed to create infra repo")
        return {"error": str(exc)}
