from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path


def create_onboarding_pr(
    repo_url: str,
    repo_name: str,
    files: list[dict],  # [{category, path, content, description}]
    branch_name: str = "agentit/onboarding",
) -> dict:
    """Clone the repo, add manifests, push branch, create PR.

    Returns {"pr_url": str, "branch": str, "files_added": int}
    or {"error": str} on failure.
    """
    tmpdir = tempfile.mkdtemp(prefix="agentit-pr-")
    try:
        repo_dir = os.path.join(tmpdir, repo_name)

        # 1. Clone
        subprocess.run(
            ["git", "clone", repo_url, repo_dir],
            check=True,
            capture_output=True,
            text=True,
        )

        # 2. Create and checkout branch
        subprocess.run(
            ["git", "checkout", "-b", branch_name],
            cwd=repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )

        # 3. Write manifest files under .agentit/{category}/
        for f in files:
            category = f["category"]
            filename = Path(f["path"]).name
            dest_dir = Path(repo_dir) / ".agentit" / category
            dest_dir.mkdir(parents=True, exist_ok=True)
            (dest_dir / filename).write_text(f["content"])

        # 4. Stage all
        subprocess.run(
            ["git", "add", ".agentit"],
            cwd=repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )

        # 5. Commit
        commit_msg = (
            "feat: add AgentIT enterprise onboarding manifests\n\n"
            "Generated by AgentIT Enterprise Readiness Platform"
        )
        subprocess.run(
            ["git", "commit", "-m", commit_msg],
            cwd=repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )

        # 6. Push
        subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            cwd=repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )

        # 7. Build PR body
        file_list = "\n".join(
            f"- `.agentit/{f['category']}/{Path(f['path']).name}` — {f['description']}"
            for f in files
        )
        pr_body = (
            "## AgentIT Enterprise Onboarding\n\n"
            "This PR adds enterprise-readiness manifests generated by AgentIT.\n\n"
            "### Generated Manifests\n"
            f"{file_list}\n\n"
            "### Categories\n"
            "- **Security**: NetworkPolicy, RBAC, SecurityContext\n"
            "- **Observability**: ServiceMonitor, Grafana Dashboard, Alerting Rules\n"
            "- **CI/CD**: Tekton Pipeline, Argo CD Application\n"
            "- **Compliance**: Kyverno Policies, SBOM Script, Compliance Evidence\n\n"
            "> Generated by [AgentIT](https://github.com/alimobrem/AgentIT)"
        )

        # 8. Create PR via gh CLI
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", "AgentIT Enterprise Onboarding",
                "--body", pr_body,
                "--head", branch_name,
            ],
            cwd=repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )

        pr_url = result.stdout.strip()
        return {"pr_url": pr_url, "branch": branch_name, "files_added": len(files)}

    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr or ""
        return {"error": f"{exc.cmd[0]} failed: {stderr.strip()}"}
    except Exception as exc:
        return {"error": str(exc)}
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
