"""Deterministic source-repo patches that clear analyzer findings.

Skills with ``delivery: source`` call here instead of emitting K8s YAML.
Each generator returns ``GeneratedFile`` values with ``target_path`` set to
a real path in the app repo (Dockerfile, package.json, audit.py, …).
"""
from __future__ import annotations

import logging
import re
import textwrap

from typing import TYPE_CHECKING

from agentit.agents.base import GeneratedFile
from agentit.models import AssessmentReport, Finding

if TYPE_CHECKING:
    from agentit.skill_engine import Skill

logger = logging.getLogger(__name__)

_LATEST_TAG_RE = re.compile(r"(FROM\s+\S+):latest(\b)", re.IGNORECASE | re.MULTILINE)


def _open_findings(report: AssessmentReport, category: str) -> list[Finding]:
    out: list[Finding] = []
    for score in report.scores:
        for finding in score.findings:
            if (finding.category or "").lower().replace("-", "_") == category:
                out.append(finding)
    return out


def _primary_language(report: AssessmentReport) -> str:
    if not report.stack.languages:
        return "python"
    return (report.stack.languages[0].name or "python").lower()


def _pin_latest_in_dockerfile(content: str) -> str:
    """Replace ``:latest`` on FROM lines with a floating major tag ``:1``.

    UBI/Node/Python images publish a ``:1`` stream that is more reproducible
    than ``:latest`` without requiring a live registry digest lookup.
    """
    return _LATEST_TAG_RE.sub(r"\1:1\2", content)


def _dockerfile_for_stack(lang: str, port: int = 8080) -> str:
    base = {
        "python": "registry.access.redhat.com/ubi9/python-312:1",
        "go": "registry.access.redhat.com/ubi9/go-toolset:1",
        "java": "registry.access.redhat.com/ubi9/openjdk-21:1",
        "node": "registry.access.redhat.com/ubi9/nodejs-20:1",
        "javascript": "registry.access.redhat.com/ubi9/nodejs-20:1",
        "typescript": "registry.access.redhat.com/ubi9/nodejs-20:1",
    }.get(lang, "registry.access.redhat.com/ubi9/ubi-minimal:1")
    return textwrap.dedent(f"""\
        FROM {base}

        WORKDIR /app
        COPY . .

        USER 1001

        EXPOSE {port}

        HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\
          CMD curl -f http://localhost:{port}/healthz || exit 1
    """)


def _containerfile_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    findings = _open_findings(report, "container")
    lang = _primary_language(report)
    # Prefer patching an existing Dockerfile path from the finding.
    target = "Dockerfile"
    for f in findings:
        if f.file_path and (
            "dockerfile" in f.file_path.lower()
            or "containerfile" in f.file_path.lower()
        ):
            target = f.file_path
            break

    content = _dockerfile_for_stack(lang)
    content = _pin_latest_in_dockerfile(content)
    addressed = findings[0].description if findings else skill.property_description

    return [GeneratedFile(
        path=f"patch-{target.replace('/', '-')}",
        content=content if content.endswith("\n") else content + "\n",
        description=f"Generated by skill {skill.name} — source Containerfile/Dockerfile patch",
        finding_addressed=addressed,
        skill_name=skill.name,
        target_path=target,
    )]


def _eol_upgrade_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    findings = _open_findings(report, "eol")
    files: list[GeneratedFile] = []
    for finding in findings:
        desc = (finding.description or "").lower()
        target = finding.file_path or ""
        if "node" in desc:
            # Never overwrite package.json wholesale (would destroy scripts/
            # deps). Pin runtime via .node-version — analyzer prefers this
            # over engines.node when present (see analyzers/eol.py).
            files.append(GeneratedFile(
                path="patch-node-version",
                content="22\n",
                description=(
                    f"Generated by skill {skill.name} — pin Node 22 "
                    f"past EOL ({finding.description})"
                ),
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=".node-version",
            ))
        elif "python" in desc:
            target = target or ".python-version"
            # Extract major.minor from finding text when present.
            ver_match = re.search(r"python\s+(\d+\.\d+)", desc)
            current = ver_match.group(1) if ver_match else "3.9"
            major, minor = current.split(".")
            bumped = f"{major}.{int(minor) + 1}" if major == "3" else "3.12"
            if float(bumped) < 3.12:
                bumped = "3.12"
            files.append(GeneratedFile(
                path="patch-python-version",
                content=f"{bumped}\n",
                description=(
                    f"Generated by skill {skill.name} — bump Python "
                    f"past EOL ({finding.description})"
                ),
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=target if target.endswith((".python-version", "runtime.txt")) else ".python-version",
            ))
        elif finding.file_path and (
            "dockerfile" in finding.file_path.lower()
            or "containerfile" in finding.file_path.lower()
        ):
            lang = _primary_language(report)
            content = _pin_latest_in_dockerfile(_dockerfile_for_stack(lang))
            files.append(GeneratedFile(
                path=f"patch-eol-{finding.file_path.replace('/', '-')}",
                content=content,
                description=f"Generated by skill {skill.name} — EOL base image bump",
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=finding.file_path,
            ))
    return files


def _app_audit_logging_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    lang = _primary_language(report)
    if lang in ("javascript", "typescript", "node"):
        target = "audit.ts"
        content = textwrap.dedent("""\
            /**
             * Application audit logging for privileged actions and data access.
             * Wire into auth / admin / data-mutation handlers.
             */
            export type AuditEvent = {
              action: string;
              actor: string;
              resource: string;
              outcome: "success" | "failure";
              metadata?: Record<string, unknown>;
            };

            export function auditLog(event: AuditEvent): void {
              const record = {
                ts: new Date().toISOString(),
                type: "audit",
                ...event,
              };
              // Structured stdout — collected by the platform log pipeline.
              console.info(JSON.stringify(record));
            }
        """)
    elif lang == "go":
        target = "audit.go"
        content = textwrap.dedent("""\
            package audit

            import (
            \t"encoding/json"
            \t"log"
            \t"time"
            )

            // Event is an application audit record for privileged actions / data access.
            type Event struct {
            \tTS       time.Time `json:"ts"`
            \tType     string    `json:"type"`
            \tAction   string    `json:"action"`
            \tActor    string    `json:"actor"`
            \tResource string    `json:"resource"`
            \tOutcome  string    `json:"outcome"`
            }

            // Log writes a structured audit event to stdout for the log pipeline.
            func Log(action, actor, resource, outcome string) {
            \te := Event{
            \t\tTS: time.Now().UTC(), Type: "audit",
            \t\tAction: action, Actor: actor, Resource: resource, Outcome: outcome,
            \t}
            \tb, _ := json.Marshal(e)
            \tlog.Println(string(b))
            }
        """)
    else:
        target = "audit.py"
        content = textwrap.dedent('''\
            """Application audit logging for privileged actions and data access."""

            from __future__ import annotations

            import json
            import logging
            from datetime import datetime, timezone
            from typing import Any

            _log = logging.getLogger("audit")


            def audit_log(
                action: str,
                *,
                actor: str,
                resource: str,
                outcome: str = "success",
                metadata: dict[str, Any] | None = None,
            ) -> None:
                """Emit a structured audit event (stdout → platform log pipeline)."""
                record = {
                    "ts": datetime.now(timezone.utc).isoformat(),
                    "type": "audit",
                    "action": action,
                    "actor": actor,
                    "resource": resource,
                    "outcome": outcome,
                }
                if metadata:
                    record["metadata"] = metadata
                _log.info("%s", json.dumps(record, default=str))
        ''')

    findings = _open_findings(report, "audit")
    addressed = findings[0].description if findings else skill.property_description
    return [GeneratedFile(
        path=f"patch-{target}",
        content=content if content.endswith("\n") else content + "\n",
        description=f"Generated by skill {skill.name} — app audit logging module",
        finding_addressed=addressed,
        skill_name=skill.name,
        target_path=target,
    )]


def _db_migration_tooling_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    lang = _primary_language(report)
    files: list[GeneratedFile] = []
    findings = _open_findings(report, "migration")
    addressed = findings[0].description if findings else skill.property_description

    if lang in ("javascript", "typescript", "node"):
        files.append(GeneratedFile(
            path="patch-migrations-readme",
            content=textwrap.dedent("""\
                # Database migrations

                This app uses a `migrations/` directory for schema changes.
                Add a migrator (e.g. `node-pg-migrate`, Prisma, Knex) and keep
                forward-only SQL/TS migrations here so deploys stay reproducible.
            """),
            description=f"Generated by skill {skill.name} — migration tooling scaffold",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="migrations/README.md",
        ))
    elif lang == "go":
        files.append(GeneratedFile(
            path="patch-migrate-readme",
            content=textwrap.dedent("""\
                # Database migrations (golang-migrate)

                Place versioned SQL migrations here (`0001_init.up.sql`, …).
                Run with [golang-migrate](https://github.com/golang-migrate/migrate).
            """),
            description=f"Generated by skill {skill.name} — golang-migrate scaffold",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="migrations/README.md",
        ))
    else:
        files.append(GeneratedFile(
            path="patch-alembic-ini",
            content=textwrap.dedent("""\
                [alembic]
                script_location = alembic
                prepend_sys_path = .
                version_path_separator = os

                [loggers]
                keys = root,sqlalchemy,alembic

                [handlers]
                keys = console

                [formatters]
                keys = generic

                [logger_root]
                level = WARN
                handlers = console

                [logger_sqlalchemy]
                level = WARN
                handlers =
                qualname = sqlalchemy.engine

                [logger_alembic]
                level = INFO
                handlers =
                qualname = alembic

                [handler_console]
                class = StreamHandler
                args = (sys.stderr,)
                level = NOTSET
                formatter = generic

                [formatter_generic]
                format = %(levelname)-5.5s [%(name)s] %(message)s
            """),
            description=f"Generated by skill {skill.name} — Alembic config",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="alembic.ini",
        ))
        files.append(GeneratedFile(
            path="patch-alembic-env",
            content=textwrap.dedent('''\
                """Alembic environment — wire `target_metadata` to your SQLAlchemy models."""

                from __future__ import annotations

                from logging.config import fileConfig

                from alembic import context
                from sqlalchemy import engine_from_config, pool

                config = context.config
                if config.config_file_name is not None:
                    fileConfig(config.config_file_name)

                # Import your model's MetaData and assign it here:
                target_metadata = None


                def run_migrations_offline() -> None:
                    url = config.get_main_option("sqlalchemy.url")
                    context.configure(
                        url=url,
                        target_metadata=target_metadata,
                        literal_binds=True,
                        dialect_opts={"paramstyle": "named"},
                    )
                    with context.begin_transaction():
                        context.run_migrations()


                def run_migrations_online() -> None:
                    connectable = engine_from_config(
                        config.get_section(config.config_ini_section, {}),
                        prefix="sqlalchemy.",
                        poolclass=pool.NullPool,
                    )
                    with connectable.connect() as connection:
                        context.configure(connection=connection, target_metadata=target_metadata)
                        with context.begin_transaction():
                            context.run_migrations()


                if context.is_offline_mode():
                    run_migrations_offline()
                else:
                    run_migrations_online()
            '''),
            description=f"Generated by skill {skill.name} — Alembic env.py",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="alembic/env.py",
        ))
    return files


def generate_source_patch_for_skill(
    skill: "Skill",
    report: AssessmentReport,
    app_name: str,
    llm_client: object | None = None,
) -> list[GeneratedFile]:
    """Dispatch to the skill-specific source patch generator."""
    del app_name, llm_client  # reserved for future LLM-tailored source patches
    generators = {
        "containerfile": _containerfile_patch,
        "eol-upgrade": _eol_upgrade_patch,
        "app-audit-logging": _app_audit_logging_patch,
        "db-migration-tooling": _db_migration_tooling_patch,
    }
    gen = generators.get(skill.name)
    if gen is None:
        from agentit.skill_engine import (
            _extract_template,
            _render_template,
            _template_variables,
        )

        # Generic: render a template fence if present, using first output
        # label as the target filename.
        template = _extract_template(skill.body)
        if not template:
            logger.info("Source skill %s has no template/generator — skipping", skill.name)
            return []
        target = skill.outputs[0] if skill.outputs else skill.name
        try:
            content = _render_template(
                template,
                _template_variables(
                    report.repo_name.lower().replace("_", "-").replace(".", "-"),
                    report,
                ),
            )
        except Exception as exc:
            logger.info("Source skill %s template failed: %s", skill.name, exc)
            return []
        return [GeneratedFile(
            path=f"patch-{target.replace('/', '-')}",
            content=content if content.endswith("\n") else content + "\n",
            description=f"Generated by skill {skill.name}",
            finding_addressed=skill.property_description,
            skill_name=skill.name,
            target_path=target,
        )]
    return gen(skill, report)
