"""Deterministic source-repo patches that clear analyzer findings.

Skills with ``delivery: source`` call here instead of emitting K8s YAML.
Each generator returns ``GeneratedFile`` values with ``target_path`` set to
a real path in the app repo (Dockerfile, package.json, audit.py, …).
"""
from __future__ import annotations

import logging
import re
import textwrap

from typing import TYPE_CHECKING

from agentit.agents.base import GeneratedFile
from agentit.models import AssessmentReport, Finding

if TYPE_CHECKING:
    from agentit.skill_engine import Skill

logger = logging.getLogger(__name__)

_LATEST_TAG_RE = re.compile(r"(FROM\s+\S+):latest(\b)", re.IGNORECASE | re.MULTILINE)


def _open_findings(report: AssessmentReport, category: str) -> list[Finding]:
    out: list[Finding] = []
    for score in report.scores:
        for finding in score.findings:
            if (finding.category or "").lower().replace("-", "_") == category:
                out.append(finding)
    return out


def _primary_language(report: AssessmentReport) -> str:
    if not report.stack.languages:
        return "python"
    return (report.stack.languages[0].name or "python").lower()


def _pin_latest_in_dockerfile(content: str) -> str:
    """Replace ``:latest`` on FROM lines with a floating major tag ``:1``.

    UBI/Node/Python images publish a ``:1`` stream that is more reproducible
    than ``:latest`` without requiring a live registry digest lookup.
    """
    return _LATEST_TAG_RE.sub(r"\1:1\2", content)


def _dockerfile_for_stack(lang: str, port: int = 8080) -> str:
    base = {
        "python": "registry.access.redhat.com/ubi9/python-312:1",
        "go": "registry.access.redhat.com/ubi9/go-toolset:1",
        "java": "registry.access.redhat.com/ubi9/openjdk-21:1",
        "node": "registry.access.redhat.com/ubi9/nodejs-20:1",
        "javascript": "registry.access.redhat.com/ubi9/nodejs-20:1",
        "typescript": "registry.access.redhat.com/ubi9/nodejs-20:1",
    }.get(lang, "registry.access.redhat.com/ubi9/ubi-minimal:1")
    return textwrap.dedent(f"""\
        FROM {base}

        WORKDIR /app
        COPY . .

        USER 1001

        EXPOSE {port}

        HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\
          CMD curl -f http://localhost:{port}/healthz || exit 1
    """)


def _containerfile_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    findings = _open_findings(report, "container")
    lang = _primary_language(report)
    # Prefer patching an existing Dockerfile path from the finding.
    target = "Dockerfile"
    for f in findings:
        if f.file_path and (
            "dockerfile" in f.file_path.lower()
            or "containerfile" in f.file_path.lower()
        ):
            target = f.file_path
            break

    content = _dockerfile_for_stack(lang)
    content = _pin_latest_in_dockerfile(content)
    addressed = findings[0].description if findings else skill.property_description

    return [GeneratedFile(
        path=f"patch-{target.replace('/', '-')}",
        content=content if content.endswith("\n") else content + "\n",
        description=f"Generated by skill {skill.name} — source Containerfile/Dockerfile patch",
        finding_addressed=addressed,
        skill_name=skill.name,
        target_path=target,
    )]


def _eol_upgrade_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    findings = _open_findings(report, "eol")
    files: list[GeneratedFile] = []
    for finding in findings:
        desc = (finding.description or "").lower()
        target = finding.file_path or ""
        if "node" in desc:
            # Never overwrite package.json wholesale (would destroy scripts/
            # deps). Pin runtime via .node-version — analyzer prefers this
            # over engines.node when present (see analyzers/eol.py).
            files.append(GeneratedFile(
                path="patch-node-version",
                content="22\n",
                description=(
                    f"Generated by skill {skill.name} — pin Node 22 "
                    f"past EOL ({finding.description})"
                ),
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=".node-version",
            ))
        elif "python" in desc:
            target = target or ".python-version"
            # Extract major.minor from finding text when present.
            ver_match = re.search(r"python\s+(\d+\.\d+)", desc)
            current = ver_match.group(1) if ver_match else "3.9"
            major, minor = current.split(".")
            bumped = f"{major}.{int(minor) + 1}" if major == "3" else "3.12"
            if float(bumped) < 3.12:
                bumped = "3.12"
            files.append(GeneratedFile(
                path="patch-python-version",
                content=f"{bumped}\n",
                description=(
                    f"Generated by skill {skill.name} — bump Python "
                    f"past EOL ({finding.description})"
                ),
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=target if target.endswith((".python-version", "runtime.txt")) else ".python-version",
            ))
        elif finding.file_path and (
            "dockerfile" in finding.file_path.lower()
            or "containerfile" in finding.file_path.lower()
        ):
            lang = _primary_language(report)
            content = _pin_latest_in_dockerfile(_dockerfile_for_stack(lang))
            files.append(GeneratedFile(
                path=f"patch-eol-{finding.file_path.replace('/', '-')}",
                content=content,
                description=f"Generated by skill {skill.name} — EOL base image bump",
                finding_addressed=finding.description,
                skill_name=skill.name,
                target_path=finding.file_path,
            ))
    return files


def _app_audit_logging_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    """Emit a language-matched audit helper.

    Delivery (``create_source_patch_pr``) relocates root modules into the
    detected FastAPI/Express package and wires middleware — required for
    the compliance analyzer's module+usage evidence check.
    """
    lang = _primary_language(report)
    if lang in ("javascript", "typescript", "node"):
        target = "audit.ts"
        content = textwrap.dedent("""\
            /**
             * Application audit logging for privileged actions and data access.
             * Wire into auth / admin / data-mutation handlers.
             */
            export type AuditEvent = {
              action: string;
              actor: string;
              resource: string;
              outcome: "success" | "failure";
              metadata?: Record<string, unknown>;
            };

            export function auditLog(event: AuditEvent): void {
              const record = {
                ts: new Date().toISOString(),
                type: "audit",
                ...event,
              };
              // Structured stdout — collected by the platform log pipeline.
              console.info(JSON.stringify(record));
            }
        """)
    elif lang == "go":
        target = "audit.go"
        content = textwrap.dedent("""\
            package audit

            import (
            \t"encoding/json"
            \t"log"
            \t"time"
            )

            // Event is an application audit record for privileged actions / data access.
            type Event struct {
            \tTS       time.Time `json:"ts"`
            \tType     string    `json:"type"`
            \tAction   string    `json:"action"`
            \tActor    string    `json:"actor"`
            \tResource string    `json:"resource"`
            \tOutcome  string    `json:"outcome"`
            }

            // Log writes a structured audit event to stdout for the log pipeline.
            func Log(action, actor, resource, outcome string) {
            \te := Event{
            \t\tTS: time.Now().UTC(), Type: "audit",
            \t\tAction: action, Actor: actor, Resource: resource, Outcome: outcome,
            \t}
            \tb, _ := json.Marshal(e)
            \tlog.Println(string(b))
            }
        """)
    else:
        target = "audit.py"
        content = textwrap.dedent('''\
            """Application audit logging for privileged actions and data access."""

            from __future__ import annotations

            import json
            import logging
            from datetime import datetime, timezone
            from typing import Any

            _log = logging.getLogger("audit")


            def audit_log(
                action: str,
                *,
                actor: str,
                resource: str,
                outcome: str = "success",
                metadata: dict[str, Any] | None = None,
            ) -> None:
                """Emit a structured audit event (stdout → platform log pipeline)."""
                record = {
                    "ts": datetime.now(timezone.utc).isoformat(),
                    "type": "audit",
                    "action": action,
                    "actor": actor,
                    "resource": resource,
                    "outcome": outcome,
                }
                if metadata:
                    record["metadata"] = metadata
                _log.info("%s", json.dumps(record, default=str))
        ''')

    findings = _open_findings(report, "audit")
    addressed = findings[0].description if findings else skill.property_description
    return [GeneratedFile(
        path=f"patch-{target}",
        content=content if content.endswith("\n") else content + "\n",
        description=f"Generated by skill {skill.name} — app audit logging module",
        finding_addressed=addressed,
        skill_name=skill.name,
        target_path=target,
    )]


def _port_for_language(lang: str) -> int:
    """Same convention already established in ``agents/codechange.py``'s
    ``_fix_dockerfile`` -- reused (not reinvented) so this skill's port
    default agrees with the rest of this codebase's own precedent."""
    return 3000 if lang in ("node", "javascript", "typescript") else 8080


_HELM_CHART_FILE_RE = re.compile(
    r"===FILE:\s*(.+?)\s*===\n(.*?)(?=\n===FILE:|\n===END===|\Z)", re.DOTALL,
)
_HELM_CHART_MAX_FILES = 8
_HELM_REQUIRED_FILE = "Chart.yaml"
_HELM_YAML_TEMPLATE_DIR = "templates/"


def _parse_llm_multi_file_response(raw: str) -> dict[str, str]:
    """Parse skill body's ``===FILE: <path>===`` delimited multi-file
    protocol. Returns ``{relative_path: content}``, capped at
    ``_HELM_CHART_MAX_FILES`` entries (defense against a runaway response)."""
    files: dict[str, str] = {}
    for match in _HELM_CHART_FILE_RE.finditer(raw or ""):
        path = match.group(1).strip().lstrip("/")
        content = match.group(2)
        if not path or not content.strip():
            continue
        files[path] = content if content.endswith("\n") else content + "\n"
        if len(files) >= _HELM_CHART_MAX_FILES:
            break
    return files


def _validate_helm_chart_files(files: dict[str, str]) -> list[str]:
    """Real validation gate for a candidate Helm chart -- every failure
    reason returned here is why this skill refuses the LLM's output and
    falls back to the deterministic template instead of shipping something
    "plausible-looking" but wrong (per the plan's "a wrong chart is worse
    than no chart" principle).
    """
    import yaml

    from agentit.agents.base import validate_manifest
    from agentit.skill_engine import _PLACEHOLDER_RE

    errors: list[str] = []
    if _HELM_REQUIRED_FILE not in files:
        errors.append(f"missing required {_HELM_REQUIRED_FILE}")
        return errors

    try:
        chart_doc = yaml.safe_load(files[_HELM_REQUIRED_FILE])
    except yaml.YAMLError as exc:
        return [f"{_HELM_REQUIRED_FILE}: YAML parse error: {exc}"]
    if not isinstance(chart_doc, dict) or not chart_doc.get("name") or not chart_doc.get("version"):
        errors.append(f"{_HELM_REQUIRED_FILE}: missing 'name' or 'version'")

    has_k8s_manifest = False
    for path, content in files.items():
        if not path.startswith(_HELM_YAML_TEMPLATE_DIR) or not path.endswith((".yaml", ".yml")):
            continue
        if "apiVersion:" in content and "kind:" in content:
            has_k8s_manifest = True
        manifest_errors = validate_manifest(content)
        if manifest_errors:
            errors.append(f"{path}: {'; '.join(manifest_errors)}")
        unresolved = sorted(set(_PLACEHOLDER_RE.findall(content)))
        if unresolved:
            errors.append(f"{path}: unresolved placeholder(s): {', '.join(unresolved)}")

    if not has_k8s_manifest:
        errors.append(
            "no templates/*.yaml file has literal 'apiVersion:'/'kind:' text "
            "-- would not clear the 'manifests' finding"
        )
    return errors


_HELM_CHART_SYSTEM_PROMPT = (
    "You are a platform engineer scaffolding a real, minimal Helm chart for "
    "an application that currently has none. Output ONLY the delimited "
    "multi-file format described in the instructions -- no commentary, no "
    "markdown fences around the whole response. Never invent a hostname, "
    "Ingress/Route, or specific environment variable names/values -- omit "
    "them rather than guess. Never use Helm control-flow directives "
    "({{- if }}, {{- range }}, {{- with }}) in templates/*.yaml -- only "
    "inline value substitutions ({{ .Values.x }}), so every file stays "
    "parseable as plain YAML. ALWAYS quote a {{ .Values.x }}/{{ .Chart.x }} "
    "substitution when it starts a YAML scalar value (e.g. "
    "replicas: \"{{ .Values.replicaCount }}\", never "
    "replicas: {{ .Values.replicaCount }}) -- unquoted, a leading {{ "
    "parses as YAML flow-mapping syntax and fails to parse."
)


def _helm_chart_llm_user_prompt(
    skill: "Skill", report: AssessmentReport, app_name: str, image_ref: str,
) -> str:
    stack = ", ".join(l.name for l in report.stack.languages) if report.stack.languages else "unknown"
    frameworks = ", ".join(f.name for f in report.stack.frameworks) if report.stack.frameworks else "none detected"
    return (
        f"Application: {app_name}\n"
        f"Stack: {stack}\n"
        f"Frameworks: {frameworks}\n"
        f"Architecture: {report.architecture.architecture_style}, "
        f"has_api={report.architecture.has_api}, api_style={report.architecture.api_style}\n"
        f"Criticality: {report.criticality}\n"
        f"Real internal registry image reference to use in values.yaml: {image_ref}\n\n"
        f"Skill instructions:\n{skill.body}\n\n"
        "Generate Chart.yaml, values.yaml, templates/deployment.yaml, and "
        "templates/service.yaml for this application, using the exact "
        "===FILE: <path>=== / ===END=== delimited format from the "
        "instructions."
    )


def _helm_chart_llm_attempt(
    skill: "Skill", report: AssessmentReport, app_name: str, image_ref: str, llm_client: object,
) -> dict[str, str] | None:
    """Two-attempt LLM generation with validation-error feedback, mirroring
    ``SkillEngine._generate_with_llm``'s own retry shape. Returns the parsed
    ``{path: content}`` map on success, or ``None`` to fall back to the
    deterministic template."""
    from agentit.llm import _SKILL_GENERATION_MAX_TOKENS

    user = _helm_chart_llm_user_prompt(skill, report, app_name, image_ref)
    for attempt in range(2):
        raw = llm_client._chat(_HELM_CHART_SYSTEM_PROMPT, user, max_tokens=_SKILL_GENERATION_MAX_TOKENS)
        if raw is None:
            return None
        parsed = _parse_llm_multi_file_response(raw)
        errors = _validate_helm_chart_files(parsed)
        if not errors:
            return parsed
        logger.info(
            "helm-chart LLM generation for %s rejected (attempt %d): %s",
            app_name, attempt + 1, errors,
        )
        user += f"\n\nYour previous output had errors: {errors}. Fix them and resend the full format."
    return None


def _helm_chart_template_fallback(
    skill: "Skill", report: AssessmentReport, app_name: str, image_ref: str,
) -> dict[str, str]:
    """Deterministic, literal-values-only chart -- no Helm ``.Values``/
    ``.Release`` indirection at all, so there is zero risk of an
    unresolved-placeholder or mismatched-values-vs-template bug. Every
    value baked in here is one this skill already has real data for
    (``app_name``, the real ``image_ref``, and the same language-based port
    convention ``agents/codechange.py::_fix_dockerfile`` already uses) --
    nothing fabricated, matching the "no mock data" rule.
    """
    lang = _primary_language(report)
    port = _port_for_language(lang)
    repo_ref, _, tag = image_ref.rpartition(":")
    tag = tag or "latest"

    chart_yaml = textwrap.dedent(f"""\
        apiVersion: v2
        name: {app_name}
        description: Helm chart for {app_name}, generated by AgentIT to satisfy IaC/manifest baselines
        type: application
        version: 0.1.0
        appVersion: "1.0.0"
    """)
    values_yaml = textwrap.dedent(f"""\
        # Real values used to render templates/*.yaml. This chart intentionally
        # uses literal values rather than Helm's `.Values`/`.Release` indirection
        # -- see skills/infrastructure/helm-chart.md for why (deterministic
        # fallback, no LLM available for app-specific tailoring).
        replicaCount: 1
        image:
          repository: {repo_ref}
          tag: "{tag}"
        service:
          port: {port}
    """)
    deployment_yaml = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {app_name}
          labels:
            app.kubernetes.io/name: {app_name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: {app_name}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: {app_name}
            spec:
              containers:
                - name: {app_name}
                  image: "{image_ref}"
                  ports:
                    - name: http
                      containerPort: {port}
                  livenessProbe:
                    tcpSocket:
                      port: http
                    initialDelaySeconds: 15
                    periodSeconds: 20
                    failureThreshold: 5
                  readinessProbe:
                    tcpSocket:
                      port: http
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    failureThreshold: 3
    """)
    service_yaml = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Service
        metadata:
          name: {app_name}
          labels:
            app.kubernetes.io/name: {app_name}
        spec:
          type: ClusterIP
          selector:
            app.kubernetes.io/name: {app_name}
          ports:
            - port: {port}
              targetPort: http
              protocol: TCP
              name: http
    """)
    return {
        "Chart.yaml": chart_yaml,
        "values.yaml": values_yaml,
        "templates/deployment.yaml": deployment_yaml,
        "templates/service.yaml": service_yaml,
    }


def _helm_chart_patch(
    skill: "Skill", report: AssessmentReport, app_name: str, llm_client: object | None = None,
) -> list[GeneratedFile]:
    """Real Helm chart (Chart.yaml + values.yaml + Deployment + Service)
    clearing infrastructure.py's ``iac`` and ``manifests`` findings in one
    PR -- see skills/infrastructure/helm-chart.md for the full design
    rationale (why one skill, why LLM-mode, why no Ingress/env vars).
    """
    from agentit.image_builder import get_image_ref

    image_ref = get_image_ref(app_name)
    files_by_path: dict[str, str] | None = None

    if llm_client is not None and hasattr(llm_client, "_chat"):
        files_by_path = _helm_chart_llm_attempt(skill, report, app_name, image_ref, llm_client)
        source_note = "LLM-tailored"

    if not files_by_path:
        files_by_path = _helm_chart_template_fallback(skill, report, app_name, image_ref)
        source_note = "deterministic template (no LLM, or LLM output failed validation)"

    findings = _open_findings(report, "iac") + _open_findings(report, "manifests")
    addressed = "; ".join(f.description for f in findings) if findings else skill.property_description

    prefix = "helm"
    out: list[GeneratedFile] = []
    for rel_path, content in files_by_path.items():
        target = f"{prefix}/{rel_path}"
        out.append(GeneratedFile(
            path=f"patch-{target.replace('/', '-')}",
            content=content,
            description=f"Generated by skill {skill.name} — {source_note} Helm chart file",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path=target,
        ))
    return out


def _db_migration_tooling_patch(skill: "Skill", report: AssessmentReport) -> list[GeneratedFile]:
    lang = _primary_language(report)
    files: list[GeneratedFile] = []
    findings = _open_findings(report, "migration")
    addressed = findings[0].description if findings else skill.property_description

    if lang in ("javascript", "typescript", "node"):
        files.append(GeneratedFile(
            path="patch-migrations-readme",
            content=textwrap.dedent("""\
                # Database migrations

                This app uses a `migrations/` directory for schema changes.
                Add a migrator (e.g. `node-pg-migrate`, Prisma, Knex) and keep
                forward-only SQL/TS migrations here so deploys stay reproducible.
            """),
            description=f"Generated by skill {skill.name} — migration tooling scaffold",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="migrations/README.md",
        ))
    elif lang == "go":
        files.append(GeneratedFile(
            path="patch-migrate-readme",
            content=textwrap.dedent("""\
                # Database migrations (golang-migrate)

                Place versioned SQL migrations here (`0001_init.up.sql`, …).
                Run with [golang-migrate](https://github.com/golang-migrate/migrate).
            """),
            description=f"Generated by skill {skill.name} — golang-migrate scaffold",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="migrations/README.md",
        ))
    else:
        files.append(GeneratedFile(
            path="patch-alembic-ini",
            content=textwrap.dedent("""\
                [alembic]
                script_location = alembic
                prepend_sys_path = .
                version_path_separator = os

                [loggers]
                keys = root,sqlalchemy,alembic

                [handlers]
                keys = console

                [formatters]
                keys = generic

                [logger_root]
                level = WARN
                handlers = console

                [logger_sqlalchemy]
                level = WARN
                handlers =
                qualname = sqlalchemy.engine

                [logger_alembic]
                level = INFO
                handlers =
                qualname = alembic

                [handler_console]
                class = StreamHandler
                args = (sys.stderr,)
                level = NOTSET
                formatter = generic

                [formatter_generic]
                format = %(levelname)-5.5s [%(name)s] %(message)s
            """),
            description=f"Generated by skill {skill.name} — Alembic config",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="alembic.ini",
        ))
        files.append(GeneratedFile(
            path="patch-alembic-env",
            content=textwrap.dedent('''\
                """Alembic environment — wire `target_metadata` to your SQLAlchemy models."""

                from __future__ import annotations

                from logging.config import fileConfig

                from alembic import context
                from sqlalchemy import engine_from_config, pool

                config = context.config
                if config.config_file_name is not None:
                    fileConfig(config.config_file_name)

                # Import your model's MetaData and assign it here:
                target_metadata = None


                def run_migrations_offline() -> None:
                    url = config.get_main_option("sqlalchemy.url")
                    context.configure(
                        url=url,
                        target_metadata=target_metadata,
                        literal_binds=True,
                        dialect_opts={"paramstyle": "named"},
                    )
                    with context.begin_transaction():
                        context.run_migrations()


                def run_migrations_online() -> None:
                    connectable = engine_from_config(
                        config.get_section(config.config_ini_section, {}),
                        prefix="sqlalchemy.",
                        poolclass=pool.NullPool,
                    )
                    with connectable.connect() as connection:
                        context.configure(connection=connection, target_metadata=target_metadata)
                        with context.begin_transaction():
                            context.run_migrations()


                if context.is_offline_mode():
                    run_migrations_offline()
                else:
                    run_migrations_online()
            '''),
            description=f"Generated by skill {skill.name} — Alembic env.py",
            finding_addressed=addressed,
            skill_name=skill.name,
            target_path="alembic/env.py",
        ))
    return files


def generate_source_patch_for_skill(
    skill: "Skill",
    report: AssessmentReport,
    app_name: str,
    llm_client: object | None = None,
) -> list[GeneratedFile]:
    """Dispatch to the skill-specific source patch generator.

    ``llm_client`` is only actually used by ``helm-chart`` (the one
    ``delivery: source`` skill that needs LLM tailoring -- see
    skills/infrastructure/helm-chart.md); every other generator here is
    deterministic and ignores it, unchanged from before.
    """
    if skill.name == "helm-chart":
        return _helm_chart_patch(skill, report, app_name, llm_client)

    generators = {
        "containerfile": _containerfile_patch,
        "eol-upgrade": _eol_upgrade_patch,
        "app-audit-logging": _app_audit_logging_patch,
        "db-migration-tooling": _db_migration_tooling_patch,
    }
    gen = generators.get(skill.name)
    if gen is None:
        from agentit.skill_engine import (
            _extract_template,
            _render_template,
            _template_variables,
        )

        # Generic: render a template fence if present, using first output
        # label as the target filename.
        template = _extract_template(skill.body)
        if not template:
            logger.info("Source skill %s has no template/generator — skipping", skill.name)
            return []
        target = skill.outputs[0] if skill.outputs else skill.name
        try:
            content = _render_template(
                template,
                _template_variables(
                    report.repo_name.lower().replace("_", "-").replace(".", "-"),
                    report,
                ),
            )
        except Exception as exc:
            logger.info("Source skill %s template failed: %s", skill.name, exc)
            return []
        return [GeneratedFile(
            path=f"patch-{target.replace('/', '-')}",
            content=content if content.endswith("\n") else content + "\n",
            description=f"Generated by skill {skill.name}",
            finding_addressed=skill.property_description,
            skill_name=skill.name,
            target_path=target,
        )]
    return gen(skill, report)
